
//1. Import Area

// Import DefaultImport from 'some library / locations'

import Head from 'next/head'

import styles from '../styles/Home.module.css'
import A from './Components/A'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Prop Drilling</title> 

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>

     <>
        <A name="Gulab" msg="OKLABS"> </A>
        
     </>
    </div>
  )
}
